name: Trigger auto deployment for python-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/python-container-app-AutoDeployTrigger-88f35396-7fd8-4109-b330-7e78ccee3c58.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PYTHONCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 202405052151pythoncontainer.azurecr.io
          registryUsername: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: python-container-app
          resourceGroup: pythoncontainer-rg
          imageToBuild: 202405052151pythoncontainer.azurecr.io/python-container-app:${{ github.sha }}
          
            

     

